---
- name: Install the required packages
  hosts: all
  sudo: yes
  vars:
    nodejs_version: 5.x
    gort_package: https://s3.amazonaws.com/gort-io/0.5.2/gort_0.5.2_amd64.deb
    apt_packages:
      - nodejs
      - build-essential
      - libbluetooth-dev
      - bluez
    apt_keys:
      - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    apt_repositories:
      - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} vivid main'
  tasks:
    - name: Add APT Keys
      apt_key: url="{{ item }}"
      with_items: apt_keys
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: apt_repositories
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
    - name: Install missing packages
      apt: name={{ item }}
      with_items: apt_packages
    - name: Set the timezone
      command: timedatectl set-timezone Europe/Vilnius
    - name: Get the gort_package
      get_url: url={{gort_package}} dest=/tmp/key.deb mode=0440
    - name: Install the gort
      apt: deb=/tmp/key.deb
    - name: start bluetooth server
      service: name=bluetooth state=started
    - name: install project dependencies
      npm: path=/vagrant
